# Generated by Django 4.2.1 on 2023-06-02 06:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SiteConfiguration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('site_name', models.CharField(default='Контракт Нерухомість', max_length=255)),
            ],
            options={
                'verbose_name': 'Налаштування сайту',
            },
        ),
    ]
