# Generated by Django 4.2.1 on 2023-06-02 07:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('props', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='siteconfiguration',
            name='google_api_key',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='API-ключ для Google Maps'),
        ),
    ]
