# Generated by Django 4.2.1 on 2023-06-03 05:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('props', '0003_siteconfiguration_crm_api'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='siteconfiguration',
            options={'verbose_name': 'Site Configuration'},
        ),
        migrations.AlterField(
            model_name='siteconfiguration',
            name='crm_api',
            field=models.URLField(blank=True, null=True, verbose_name='CRM-feed for parsing'),
        ),
        migrations.AlterField(
            model_name='siteconfiguration',
            name='google_api_key',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='API-key for Google Maps'),
        ),
        migrations.AlterField(
            model_name='siteconfiguration',
            name='site_name',
            field=models.CharField(default='Contract Real Estate', max_length=255),
        ),
    ]
