# Generated by Django 4.2.1 on 2023-06-19 12:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('props', '0004_alter_siteconfiguration_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='siteconfiguration',
            name='email',
            field=models.EmailField(default='example@mail.com', max_length=254, verbose_name='Email'),
        ),
    ]
