# Generated by Django 4.2.1 on 2023-07-09 08:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('props', '0005_siteconfiguration_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='siteconfiguration',
            name='site_name',
            field=models.CharField(default='Contract Real Estate', max_length=255, verbose_name='Site name'),
        ),
    ]
