# Generated by Django 4.2.1 on 2023-07-09 19:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('props', '0008_siteconfiguration_site_name_en_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='siteconfiguration',
            name='translation_api_key',
            field=models.CharField(blank=True, help_text='<a href="https://lingvanex.com/">lingvanex.com</a>', max_length=255, null=True, verbose_name='API-key for translating service'),
        ),
    ]
