# Generated by Django 4.2.1 on 2023-07-12 07:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('props', '0009_siteconfiguration_translation_api_key'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='siteconfiguration',
            name='translation_api_key',
        ),
        migrations.AddField(
            model_name='siteconfiguration',
            name='azure_location',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Location for Azure Translation'),
        ),
        migrations.AddField(
            model_name='siteconfiguration',
            name='azure_secret_key',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='API-key for Azure Translation'),
        ),
    ]
