# Generated by Django 4.2.1 on 2023-07-12 07:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('props', '0010_remove_siteconfiguration_translation_api_key_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Feed',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('feed_url', models.URLField(verbose_name='CRM-feed for parsing')),
            ],
        ),
        migrations.RemoveField(
            model_name='siteconfiguration',
            name='crm_api',
        ),
    ]
