# Generated by Django 4.2.1 on 2023-07-12 07:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('props', '0011_feed_remove_siteconfiguration_crm_api'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feed',
            name='feed_url',
            field=models.URLField(unique=True, verbose_name='CRM-feed for parsing'),
        ),
    ]
