# Generated by Django 4.2.1 on 2023-07-25 05:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('props', '0012_alter_feed_feed_url'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='feed',
            options={'verbose_name': 'Feed', 'verbose_name_plural': 'Feeds'},
        ),
    ]
