# Generated by Django 4.2.1 on 2024-01-07 12:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('props', '0013_alter_feed_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='siteconfiguration',
            name='site_name_ru',
            field=models.CharField(default='Контракт недвижимость', max_length=255, verbose_name='Site name (Russian)'),
        ),
    ]
