# Generated by Django 4.2.1 on 2023-06-02 07:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='advuser',
            options={'verbose_name': 'Профіль', 'verbose_name_plural': 'Профілі'},
        ),
    ]
