# Generated by Django 4.2.1 on 2023-06-03 05:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0002_alter_advuser_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='advuser',
            options={'verbose_name': 'Profile', 'verbose_name_plural': 'Profiles'},
        ),
    ]
