# Generated by Django 4.2.1 on 2023-07-09 13:52

import ckeditor_uploader.fields
from django.db import migrations, models
import django.db.models.deletion
import parler.fields
import parler.models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0006_alter_news_body'),
    ]

    operations = [
        migrations.CreateModel(
            name='NewsTranslation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language_code', models.CharField(db_index=True, max_length=15, verbose_name='Language')),
                ('title', models.CharField(max_length=255, verbose_name='Title')),
                ('slug', models.SlugField(max_length=255, unique=True, verbose_name='Slug')),
                ('body', ckeditor_uploader.fields.RichTextUploadingField(verbose_name='Text')),
            ],
            options={
                'verbose_name': 'News Translation',
                'db_table': 'news_news_translation',
                'db_tablespace': '',
                'managed': True,
                'default_permissions': (),
            },
            bases=(parler.models.TranslatableModel, models.Model),
        ),
        migrations.AlterModelOptions(
            name='news',
            options={'ordering': ['-created'], 'verbose_name': 'News', 'verbose_name_plural': 'News'},
        ),
        migrations.RemoveField(
            model_name='news',
            name='body',
        ),
        migrations.RemoveField(
            model_name='news',
            name='slug',
        ),
        migrations.RemoveField(
            model_name='news',
            name='title',
        ),
        migrations.AddIndex(
            model_name='news',
            index=models.Index(fields=['-created'], name='news_news_created_d2ca43_idx'),
        ),
        migrations.AddField(
            model_name='newstranslation',
            name='master',
            field=parler.fields.TranslationsForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='translations', to='news.news'),
        ),
        migrations.AlterUniqueTogether(
            name='newstranslation',
            unique_together={('language_code', 'master')},
        ),
    ]
