# Generated by Django 4.2.1 on 2023-07-09 14:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0007_newstranslation_alter_news_options_remove_news_body_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='newstranslation',
            name='slug',
        ),
    ]
