# Generated by Django 4.2.1 on 2023-06-20 15:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='News',
            new_name='Analytic',
        ),
        migrations.AlterModelOptions(
            name='analytic',
            options={'verbose_name': 'Analytic', 'verbose_name_plural': 'Analytics'},
        ),
    ]
