# Generated by Django 4.2.1 on 2023-07-09 08:06

import ckeditor_uploader.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0005_alter_analytic_body'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='analytic',
            options={'verbose_name': 'Analytical review', 'verbose_name_plural': 'Analytical reviews'},
        ),
        migrations.AlterField(
            model_name='analytic',
            name='body',
            field=ckeditor_uploader.fields.RichTextUploadingField(verbose_name='Text'),
        ),
    ]
