# Generated by Django 4.2.1 on 2023-07-09 13:52

import ckeditor_uploader.fields
from django.db import migrations, models
import django.db.models.deletion
import parler.fields
import parler.models


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0006_alter_analytic_options_alter_analytic_body'),
    ]

    operations = [
        migrations.CreateModel(
            name='AnalyticTranslation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language_code', models.CharField(db_index=True, max_length=15, verbose_name='Language')),
                ('title', models.CharField(max_length=255, verbose_name='Title')),
                ('slug', models.SlugField(max_length=255, unique=True, verbose_name='Slug')),
                ('body', ckeditor_uploader.fields.RichTextUploadingField(verbose_name='Text')),
            ],
            options={
                'verbose_name': 'Analytical review Translation',
                'db_table': 'analytics_analytic_translation',
                'db_tablespace': '',
                'managed': True,
                'default_permissions': (),
            },
            bases=(parler.models.TranslatableModel, models.Model),
        ),
        migrations.AlterModelOptions(
            name='analytic',
            options={'ordering': ['-created'], 'verbose_name': 'Analytical review', 'verbose_name_plural': 'Analytical reviews'},
        ),
        migrations.RemoveField(
            model_name='analytic',
            name='body',
        ),
        migrations.RemoveField(
            model_name='analytic',
            name='slug',
        ),
        migrations.RemoveField(
            model_name='analytic',
            name='title',
        ),
        migrations.AddIndex(
            model_name='analytic',
            index=models.Index(fields=['-created'], name='analytics_a_created_542132_idx'),
        ),
        migrations.AddField(
            model_name='analytictranslation',
            name='master',
            field=parler.fields.TranslationsForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='translations', to='analytics.analytic'),
        ),
        migrations.AlterUniqueTogether(
            name='analytictranslation',
            unique_together={('language_code', 'master')},
        ),
    ]
