# Generated by Django 4.2.1 on 2023-06-03 08:41

import django.contrib.gis.db.models.fields
import django.contrib.gis.geos.point
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0002_image_image_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listing',
            name='coordinates',
            field=django.contrib.gis.db.models.fields.PointField(default=django.contrib.gis.geos.point.Point(0.0, 0.0), srid=4326),
        ),
        migrations.AlterField(
            model_name='listing',
            name='title',
            field=models.CharField(default='', max_length=255, verbose_name='Title'),
        ),
    ]
