# Generated by Django 4.2.1 on 2023-06-03 08:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0004_alter_listing_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listing',
            name='realty_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='listings', to='listings.realtytype', verbose_name='Realty type'),
        ),
    ]
