# Generated by Django 4.2.1 on 2023-06-04 10:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0007_city_alter_listing_managers_alter_image_file_street_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='city',
            options={'verbose_name': 'City', 'verbose_name_plural': 'Cities'},
        ),
        migrations.AlterModelOptions(
            name='street',
            options={'verbose_name': 'Street', 'verbose_name_plural': 'Streets'},
        ),
        migrations.AlterUniqueTogether(
            name='kit',
            unique_together={('listing', 'attribute')},
        ),
    ]
