# Generated by Django 4.2.1 on 2023-06-04 11:07

import django.contrib.gis.db.models.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0008_alter_city_options_alter_street_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Country',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, unique=True, verbose_name='Country')),
            ],
            options={
                'verbose_name': 'Country',
                'verbose_name_plural': 'Countries',
            },
        ),
        migrations.AlterField(
            model_name='city',
            name='coordinates',
            field=django.contrib.gis.db.models.fields.PointField(srid=4326, unique=True, verbose_name='Coordinates'),
        ),
        migrations.AlterUniqueTogether(
            name='street',
            unique_together={('title', 'city')},
        ),
        migrations.AddField(
            model_name='city',
            name='country',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='listings.country', verbose_name='Country'),
        ),
    ]
