# Generated by Django 4.2.1 on 2023-06-05 05:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0011_manager_listing_manager_phone'),
    ]

    operations = [
        migrations.AddField(
            model_name='manager',
            name='image_url',
            field=models.URLField(blank=True, null=True, verbose_name='Image url'),
        ),
    ]
