# Generated by Django 4.2.1 on 2023-06-05 06:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('managers', '0001_initial'),
        ('listings', '0012_manager_image_url'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='phone',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='phone',
            name='manager',
        ),
        migrations.AlterField(
            model_name='listing',
            name='manager',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='managers.manager', verbose_name='Manager'),
        ),
        migrations.DeleteModel(
            name='Manager',
        ),
        migrations.DeleteModel(
            name='Phone',
        ),
    ]
