# Generated by Django 4.2.1 on 2023-06-06 14:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0014_alter_kit_attribute_alter_kit_listing'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='attribute',
            options={'verbose_name': 'Attribute', 'verbose_name_plural': 'Attributes'},
        ),
        migrations.AlterModelOptions(
            name='kit',
            options={'ordering': ('attribute__title',), 'verbose_name': 'Kit', 'verbose_name_plural': 'Kits'},
        ),
    ]
