# Generated by Django 4.2.1 on 2023-06-07 05:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0015_alter_attribute_options_alter_kit_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='listing',
            name='house_num',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='House Number'),
        ),
    ]
