# Generated by Django 4.2.1 on 2023-06-07 06:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0016_listing_house_num'),
    ]

    operations = [
        migrations.RenameField(
            model_name='listing',
            old_name='house_num',
            new_name='street_number',
        ),
    ]
