# Generated by Django 4.2.1 on 2023-06-10 13:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0017_rename_house_num_listing_street_number_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='city',
            name='place_id',
            field=models.CharField(max_length=255, unique=True, verbose_name='Place id'),
        ),
        migrations.AlterField(
            model_name='country',
            name='place_id',
            field=models.CharField(max_length=255, unique=True, verbose_name='Place id'),
        ),
        migrations.AlterField(
            model_name='street',
            name='place_id',
            field=models.CharField(max_length=255, unique=True, verbose_name='Place id'),
        ),
    ]
