# Generated by Django 4.2.1 on 2023-06-10 15:06

import django.contrib.gis.db.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0020_remove_city_coordinates_alter_city_title_and_more'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='city',
            name='listings_ci_place_i_7b6325_idx',
        ),
        migrations.RemoveIndex(
            model_name='country',
            name='listings_co_place_i_b204c7_idx',
        ),
        migrations.RemoveIndex(
            model_name='street',
            name='listings_st_place_i_4824b4_idx',
        ),
        migrations.RemoveField(
            model_name='city',
            name='place_id',
        ),
        migrations.RemoveField(
            model_name='country',
            name='place_id',
        ),
        migrations.AddField(
            model_name='city',
            name='coordinates',
            field=django.contrib.gis.db.models.fields.PointField(blank=True, null=True, srid=4326, verbose_name='Coordinates'),
        ),
        migrations.AlterField(
            model_name='city',
            name='title',
            field=models.CharField(max_length=255, verbose_name='City'),
        ),
        migrations.AlterField(
            model_name='country',
            name='title',
            field=models.CharField(max_length=100, unique=True, verbose_name='Country'),
        ),
        migrations.AlterField(
            model_name='street',
            name='title',
            field=models.CharField(max_length=255, verbose_name='Street'),
        ),
        migrations.AlterUniqueTogether(
            name='street',
            unique_together={('title', 'city')},
        ),
        migrations.RemoveField(
            model_name='street',
            name='place_id',
        ),
    ]
