# Generated by Django 4.2.1 on 2023-06-11 04:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0021_remove_city_listings_ci_place_i_7b6325_idx_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='city',
            name='coordinates',
        ),
        migrations.AddField(
            model_name='city',
            name='formatted_address',
            field=models.CharField(blank=True, max_length=300, null=True, verbose_name='Formatted Address'),
        ),
        migrations.AddField(
            model_name='country',
            name='formatted_address',
            field=models.CharField(blank=True, max_length=300, null=True, verbose_name='Formatted Address'),
        ),
        migrations.AddField(
            model_name='street',
            name='formatted_address',
            field=models.CharField(blank=True, max_length=300, null=True, verbose_name='Formatted Address'),
        ),
        migrations.AlterField(
            model_name='country',
            name='title',
            field=models.CharField(max_length=100, verbose_name='Country'),
        ),
    ]
