# Generated by Django 4.2.1 on 2023-06-11 06:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0022_remove_city_coordinates_city_formatted_address_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='street',
            unique_together=set(),
        ),
    ]
