# Generated by Django 4.2.1 on 2023-06-14 08:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0024_remove_country_formatted_address_alter_country_title_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'ordering': ['slug']},
        ),
        migrations.AlterModelOptions(
            name='realtytype',
            options={'verbose_name': 'Realty Type', 'verbose_name_plural': 'Realty Types'},
        ),
        migrations.AlterField(
            model_name='category',
            name='slug',
            field=models.SlugField(max_length=255, unique=True, verbose_name='Slug'),
        ),
        migrations.AlterField(
            model_name='realtytype',
            name='slug',
            field=models.SlugField(max_length=255, unique=True, verbose_name='Slug'),
        ),
        migrations.AddIndex(
            model_name='category',
            index=models.Index(fields=['slug'], name='listings_ca_slug_d576fb_idx'),
        ),
    ]
