# Generated by Django 4.2.1 on 2023-06-17 16:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0025_alter_category_options_alter_realtytype_options_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='kit',
            unique_together={('attribute', 'value')},
        ),
        migrations.RemoveField(
            model_name='kit',
            name='listing',
        ),
        migrations.AddField(
            model_name='kit',
            name='listing',
            field=models.ManyToManyField(related_name='kits', to='listings.listing', verbose_name='Listing'),
        ),
    ]
