# Generated by Django 4.2.1 on 2023-07-04 10:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0027_deal_alter_category_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='listing',
            name='video_url',
            field=models.URLField(blank=True, null=True, verbose_name='Video'),
        ),
    ]
