# Generated by Django 4.2.1 on 2023-07-04 12:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0028_listing_video_url'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='kit',
            options={'ordering': ('attribute__title', 'value'), 'verbose_name': 'Kit', 'verbose_name_plural': 'Kits'},
        ),
    ]
