# Generated by Django 4.2.1 on 2023-07-04 12:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0029_alter_kit_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='kit',
            options={'ordering': ('attribute__title',), 'verbose_name': 'Kit', 'verbose_name_plural': 'Kits'},
        ),
        migrations.AddIndex(
            model_name='kit',
            index=models.Index(fields=['value'], name='listings_ki_value_c9ad65_idx'),
        ),
    ]
