# Generated by Django 4.2.1 on 2023-07-05 10:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0030_alter_kit_options_kit_listings_ki_value_c9ad65_idx'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='menu_label',
            field=models.CharField(blank=True, max_length=300, null=True, verbose_name='Menu label'),
        ),
        migrations.AddField(
            model_name='deal',
            name='menu_label',
            field=models.CharField(blank=True, max_length=300, null=True, verbose_name='Menu label'),
        ),
        migrations.AddField(
            model_name='realtytype',
            name='menu_label',
            field=models.CharField(blank=True, max_length=300, null=True, verbose_name='Menu label'),
        ),
    ]
