# Generated by Django 4.2.1 on 2023-07-10 13:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0035_attributetranslation_kittranslation_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='kit',
            name='untranslated_value',
            field=models.CharField(default=2, max_length=255),
            preserve_default=False,
        ),
    ]
