# Generated by Django 4.2.1 on 2023-08-01 04:28

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0041_alter_listing_coordinates'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listing',
            name='created',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Created'),
        ),
        migrations.AlterField(
            model_name='listing',
            name='updated',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Updated'),
        ),
    ]
