# Generated by Django 4.2.1 on 2023-08-14 09:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0042_alter_listing_created_alter_listing_updated'),
    ]

    operations = [
        migrations.AddField(
            model_name='listingtranslation',
            name='district',
            field=models.CharField(blank=True, default='', max_length=255, null=True, verbose_name='District'),
        ),
        migrations.AddField(
            model_name='listingtranslation',
            name='housing_complex',
            field=models.CharField(blank=True, default='', max_length=255, null=True, verbose_name='Housing Complex'),
        ),
        migrations.AddField(
            model_name='listingtranslation',
            name='metro',
            field=models.CharField(blank=True, default='', max_length=255, null=True, verbose_name='Metro'),
        ),
    ]
