# Generated by Django 4.2.1 on 2023-08-16 08:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0045_district_housecomplex_alter_regiontranslation_title_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='district',
            options={'verbose_name': 'District', 'verbose_name_plural': 'Districts'},
        ),
        migrations.AddField(
            model_name='listingtranslation',
            name='metros',
            field=models.TextField(blank=True, null=True, verbose_name='Metros'),
        ),
    ]
