# Generated by Django 4.2.1 on 2023-08-22 08:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0046_alter_district_options_listingtranslation_metros'),
    ]

    operations = [
        migrations.AddField(
            model_name='listing',
            name='currency',
            field=models.CharField(default='$', max_length=1),
        ),
    ]
