# Generated by Django 4.2.1 on 2023-09-20 06:14

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0048_alter_listing_currency'),
    ]

    operations = [
        migrations.AddField(
            model_name='realtytype',
            name='slug',
            field=models.SlugField(default=django.utils.timezone.now, max_length=255, verbose_name='Slug'),
            preserve_default=False,
        ),
    ]
