# Generated by Django 4.2.1 on 2024-01-11 12:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0049_realtytype_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='image',
            name='order',
            field=models.PositiveSmallIntegerField(default=1),
        ),
    ]
