# Generated by Django 4.2.1 on 2024-01-11 13:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0050_image_order'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='image',
            options={'ordering': ['order']},
        ),
    ]
