# Generated by Django 4.2.1 on 2023-07-09 08:06

import ckeditor_uploader.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('discounts', '0004_alter_discount_body'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='discount',
            options={'verbose_name': 'Discount', 'verbose_name_plural': 'Discounts'},
        ),
        migrations.AlterField(
            model_name='discount',
            name='body',
            field=ckeditor_uploader.fields.RichTextUploadingField(verbose_name='Text'),
        ),
        migrations.AlterField(
            model_name='discount',
            name='excerpt',
            field=models.TextField(max_length=300, verbose_name='Short description'),
        ),
    ]
