# Generated by Django 4.2.1 on 2023-07-09 13:52

import ckeditor_uploader.fields
from django.db import migrations, models
import django.db.models.deletion
import parler.fields
import parler.models


class Migration(migrations.Migration):

    dependencies = [
        ('discounts', '0005_alter_discount_options_alter_discount_body_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='DiscountTranslation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language_code', models.CharField(db_index=True, max_length=15, verbose_name='Language')),
                ('title', models.CharField(max_length=255, verbose_name='Title')),
                ('slug', models.SlugField(max_length=255, unique=True, verbose_name='Slug')),
                ('body', ckeditor_uploader.fields.RichTextUploadingField(verbose_name='Text')),
                ('excerpt', models.TextField(max_length=300, verbose_name='Short description')),
            ],
            options={
                'verbose_name': 'Discount Translation',
                'db_table': 'discounts_discount_translation',
                'db_tablespace': '',
                'managed': True,
                'default_permissions': (),
            },
            bases=(parler.models.TranslatableModel, models.Model),
        ),
        migrations.AlterModelOptions(
            name='discount',
            options={'ordering': ['-created'], 'verbose_name': 'Discount', 'verbose_name_plural': 'Discounts'},
        ),
        migrations.RemoveField(
            model_name='discount',
            name='body',
        ),
        migrations.RemoveField(
            model_name='discount',
            name='excerpt',
        ),
        migrations.RemoveField(
            model_name='discount',
            name='slug',
        ),
        migrations.RemoveField(
            model_name='discount',
            name='title',
        ),
        migrations.AddIndex(
            model_name='discount',
            index=models.Index(fields=['-created'], name='discounts_d_created_0d2fb2_idx'),
        ),
        migrations.AddField(
            model_name='discounttranslation',
            name='master',
            field=parler.fields.TranslationsForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='translations', to='discounts.discount'),
        ),
        migrations.AlterUniqueTogether(
            name='discounttranslation',
            unique_together={('language_code', 'master')},
        ),
    ]
