# Generated by Django 4.2.1 on 2023-06-05 08:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('managers', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='manager',
            name='experience',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='Experience'),
        ),
        migrations.AddField(
            model_name='manager',
            name='has_car',
            field=models.BooleanField(default=False, verbose_name='Has Car?'),
        ),
    ]
