# Generated by Django 4.2.1 on 2023-06-05 08:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('managers', '0002_manager_experience_manager_has_car'),
    ]

    operations = [
        migrations.AddField(
            model_name='manager',
            name='about',
            field=models.TextField(blank=True, null=True, verbose_name='About'),
        ),
    ]
