# Generated by Django 4.2.1 on 2023-06-06 14:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('managers', '0003_manager_about'),
    ]

    operations = [
        migrations.AlterField(
            model_name='manager',
            name='full_name',
            field=models.CharField(db_index=True, max_length=255, verbose_name='Name'),
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('author', models.CharField(verbose_name='Author')),
                ('body', models.TextField(max_length=250, verbose_name='Review')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('manager', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='managers.manager', verbose_name='Manager')),
            ],
            options={
                'verbose_name': 'Review',
                'verbose_name_plural': 'Reviews',
                'ordering': ('-created',),
            },
        ),
    ]
