# Generated by Django 4.2.1 on 2023-07-09 08:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('managers', '0006_alter_review_rating'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='manager',
            options={'verbose_name': 'Manager', 'verbose_name_plural': 'Managers'},
        ),
        migrations.AlterField(
            model_name='manager',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='managers/%Y/%m/%d', verbose_name='Image'),
        ),
        migrations.AlterField(
            model_name='phone',
            name='manager',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='phones', to='managers.manager', verbose_name='Manager'),
        ),
        migrations.AlterField(
            model_name='review',
            name='created',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Created'),
        ),
    ]
