# Generated by Django 4.2.1 on 2023-07-09 17:04

from django.db import migrations, models
import django.db.models.deletion
import parler.fields
import parler.models


class Migration(migrations.Migration):

    dependencies = [
        ('managers', '0007_alter_manager_options_alter_manager_image_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='manager',
            name='about',
        ),
        migrations.RemoveField(
            model_name='manager',
            name='full_name',
        ),
        migrations.CreateModel(
            name='ManagerTranslation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language_code', models.CharField(db_index=True, max_length=15, verbose_name='Language')),
                ('full_name', models.CharField(max_length=255, verbose_name='Name')),
                ('about', models.TextField(blank=True, null=True, verbose_name='About')),
                ('master', parler.fields.TranslationsForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='translations', to='managers.manager')),
            ],
            options={
                'verbose_name': 'Manager Translation',
                'db_table': 'managers_manager_translation',
                'db_tablespace': '',
                'managed': True,
                'default_permissions': (),
                'unique_together': {('language_code', 'master')},
            },
            bases=(parler.models.TranslatableModel, models.Model),
        ),
    ]
