# Generated by Django 4.2.1 on 2023-07-09 08:06

from django.db import migrations, models
import django.db.models.deletion
import parler.fields
import parler.models


class Migration(migrations.Migration):

    dependencies = [
        ('vacantions', '0003_alter_department_title'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='department',
            options={'verbose_name': 'Department', 'verbose_name_plural': 'Departments'},
        ),
        migrations.AlterModelOptions(
            name='vacantion',
            options={'ordering': ('-created',), 'verbose_name': 'Vacantion', 'verbose_name_plural': 'Vacantions'},
        ),
        migrations.RemoveField(
            model_name='department',
            name='title',
        ),
        migrations.RemoveField(
            model_name='vacantion',
            name='description',
        ),
        migrations.RemoveField(
            model_name='vacantion',
            name='salary',
        ),
        migrations.RemoveField(
            model_name='vacantion',
            name='title',
        ),
        migrations.AlterField(
            model_name='vacantion',
            name='created',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Created'),
        ),
        migrations.AlterField(
            model_name='vacantion',
            name='department',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vacantions.department', verbose_name='Department'),
        ),
        migrations.CreateModel(
            name='VacantionTranslation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language_code', models.CharField(db_index=True, max_length=15, verbose_name='Language')),
                ('title', models.CharField(max_length=255, verbose_name='Title')),
                ('salary', models.CharField(max_length=30, verbose_name='Salary')),
                ('description', models.TextField(max_length=500, verbose_name='Description')),
                ('master', parler.fields.TranslationsForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='translations', to='vacantions.vacantion')),
            ],
            options={
                'verbose_name': 'Vacantion Translation',
                'db_table': 'vacantions_vacantion_translation',
                'db_tablespace': '',
                'managed': True,
                'default_permissions': (),
                'unique_together': {('language_code', 'master')},
            },
            bases=(parler.models.TranslatableModel, models.Model),
        ),
        migrations.CreateModel(
            name='DepartmentTranslation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language_code', models.CharField(db_index=True, max_length=15, verbose_name='Language')),
                ('title', models.CharField(max_length=100, unique=True, verbose_name='Title')),
                ('master', parler.fields.TranslationsForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='translations', to='vacantions.department')),
            ],
            options={
                'verbose_name': 'Department Translation',
                'db_table': 'vacantions_department_translation',
                'db_tablespace': '',
                'managed': True,
                'default_permissions': (),
                'unique_together': {('language_code', 'master')},
            },
            bases=(parler.models.TranslatableModel, models.Model),
        ),
    ]
