# Generated by Django 4.2.1 on 2023-07-09 09:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vacantions', '0004_alter_department_options_alter_vacantion_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='vacantion',
            options={'ordering': ('-created',), 'verbose_name': 'Vacancy', 'verbose_name_plural': 'Vacancies'},
        ),
        migrations.AlterModelOptions(
            name='vacantiontranslation',
            options={'default_permissions': (), 'managed': True, 'verbose_name': 'Vacancy Translation'},
        ),
    ]
