# Generated by Django 4.2.1 on 2024-02-23 08:45

import ckeditor_uploader.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vacantions', '0006_alter_vacantiontranslation_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vacantiontranslation',
            name='description',
            field=ckeditor_uploader.fields.RichTextUploadingField(verbose_name='Description'),
        ),
    ]
