# Generated by Django 4.2.1 on 2023-06-19 08:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='aboutitem',
            name='size',
            field=models.CharField(choices=[('about-item_third', '1/3'), ('about-item_half', '1/2'), ('about-item_full', '1/1')], default='about-item_half', max_length=16, verbose_name='Розмір (в колонках)'),
        ),
    ]
