# Generated by Django 4.2.1 on 2023-06-19 13:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0002_aboutitem_size'),
    ]

    operations = [
        migrations.CreateModel(
            name='Abroad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Заголовок')),
                ('description', models.TextField(max_length=300, verbose_name='Опис')),
            ],
            options={
                'verbose_name': 'Нерухомість закордоном',
                'verbose_name_plural': 'Нерухомість закордоном',
            },
        ),
        migrations.CreateModel(
            name='AbroadItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title_bg', models.CharField(max_length=15, verbose_name='Заголовок на фоні')),
                ('title', models.CharField(max_length=100, verbose_name='Заголовок')),
                ('description', models.TextField(max_length=500, verbose_name='Опис')),
                ('link', models.URLField(verbose_name='Посилання')),
                ('background_image', models.ImageField(upload_to='abroad_properties/%Y/%m/%d', verbose_name='Фон')),
                ('photo_1', models.ImageField(upload_to='abroad_properties/%Y/%m/%d', verbose_name='Фото 1')),
                ('photo_2', models.ImageField(upload_to='abroad_properties/%Y/%m/%d', verbose_name='Фото 2')),
                ('order', models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='Порядок')),
                ('abroad', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='pages.abroad')),
            ],
            options={
                'verbose_name': 'Нерухомість закордоном (елемент)',
                'verbose_name_plural': 'Нерухомість закордоном (елемент)',
                'ordering': ('order',),
            },
        ),
    ]
