# Generated by Django 4.2.1 on 2023-06-22 07:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0003_abroad_abroaditem'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone_1', models.CharField(max_length=30, verbose_name='Телефон 1')),
                ('phone_2', models.CharField(max_length=30, verbose_name='Телефон 2')),
                ('email', models.EmailField(max_length=254, verbose_name='Пошта')),
                ('schedule', models.CharField(max_length=255, verbose_name='Режим роботи')),
                ('office_1', models.CharField(max_length=255, verbose_name='Офіс 1')),
                ('office_2', models.CharField(max_length=255, verbose_name='Офіс 2')),
                ('office_3', models.CharField(max_length=255, verbose_name='Офіс 3')),
                ('telegram', models.URLField(blank=True, null=True, verbose_name='Телеграм')),
                ('viber', models.URLField(blank=True, null=True, verbose_name='Вайбер')),
                ('instagram', models.URLField(blank=True, null=True, verbose_name='Інстаграм')),
                ('facebook', models.URLField(blank=True, null=True, verbose_name='Фейсбук')),
            ],
            options={
                'verbose_name': 'Контакт',
                'verbose_name_plural': 'Контакти',
            },
        ),
    ]
