# Generated by Django 4.2.1 on 2023-06-22 10:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0004_contact'),
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('register_link', models.URLField(blank=True, null=True, verbose_name='Зсилка на реєстрацію')),
                ('auth_link', models.URLField(blank=True, null=True, verbose_name='Зсилка на авторизацію')),
            ],
            options={
                'verbose_name': 'Курс',
                'verbose_name_plural': 'Курс',
            },
        ),
        migrations.AlterModelOptions(
            name='contact',
            options={'verbose_name': 'Контакти', 'verbose_name_plural': 'Контакти'},
        ),
    ]
