# Generated by Django 4.2.1 on 2023-06-28 13:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0005_course_alter_contact_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='VacantionPage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('video', models.FileField(upload_to='vacantions/%Y/%m/%d', verbose_name='Video')),
            ],
            options={
                'verbose_name': 'Вакасії',
                'verbose_name_plural': 'Вакасії',
            },
        ),
    ]
