# Generated by Django 4.2.1 on 2023-06-28 13:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0007_alter_vacantionpage_video'),
    ]

    operations = [
        migrations.AddField(
            model_name='vacantionpage',
            name='poster',
            field=models.FileField(blank=True, null=True, upload_to='vacantions/%Y/%m/%d', verbose_name='Poster'),
        ),
    ]
