# Generated by Django 4.2.1 on 2023-07-03 06:15

import ckeditor_uploader.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0008_vacantionpage_poster'),
    ]

    operations = [
        migrations.CreateModel(
            name='Home',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('about', ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True, verbose_name='Про нас секція')),
            ],
            options={
                'verbose_name': 'Головна',
                'verbose_name_plural': 'Головна',
            },
        ),
    ]
