# Generated by Django 4.2.1 on 2023-07-03 06:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0009_home'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='vacantionpage',
            options={'verbose_name': 'Вакансії', 'verbose_name_plural': 'Вакансії'},
        ),
        migrations.AddField(
            model_name='home',
            name='title',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='Заголовок'),
        ),
    ]
