# Generated by Django 4.2.1 on 2023-07-09 08:06

import ckeditor_uploader.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0010_alter_vacantionpage_options_home_title'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='about',
            options={'verbose_name': 'About us', 'verbose_name_plural': 'About us'},
        ),
        migrations.AlterModelOptions(
            name='aboutitem',
            options={'ordering': ('order',), 'verbose_name': 'About us detail', 'verbose_name_plural': 'About us details'},
        ),
        migrations.AlterModelOptions(
            name='abroad',
            options={'verbose_name': 'Real estate abroad', 'verbose_name_plural': 'Real estate abroad'},
        ),
        migrations.AlterModelOptions(
            name='abroaditem',
            options={'ordering': ('order',), 'verbose_name': 'Real estate element', 'verbose_name_plural': 'Real estate element'},
        ),
        migrations.AlterModelOptions(
            name='contact',
            options={'verbose_name': 'Contacts', 'verbose_name_plural': 'Contacts'},
        ),
        migrations.AlterModelOptions(
            name='course',
            options={'verbose_name': 'Course', 'verbose_name_plural': 'Course'},
        ),
        migrations.AlterModelOptions(
            name='home',
            options={'verbose_name': 'Home', 'verbose_name_plural': 'Home'},
        ),
        migrations.AlterModelOptions(
            name='vacantionpage',
            options={'verbose_name': 'Vacantions', 'verbose_name_plural': 'Vacantions'},
        ),
        migrations.AlterField(
            model_name='about',
            name='description_1',
            field=models.TextField(max_length=300, verbose_name='Description 1 of the section'),
        ),
        migrations.AlterField(
            model_name='about',
            name='description_2',
            field=models.TextField(max_length=300, verbose_name='Description 2 of the section'),
        ),
        migrations.AlterField(
            model_name='about',
            name='title_1',
            field=models.CharField(max_length=255, verbose_name='Title 1 of the section'),
        ),
        migrations.AlterField(
            model_name='about',
            name='title_2',
            field=models.CharField(max_length=255, verbose_name='Title 2 of the section'),
        ),
        migrations.AlterField(
            model_name='aboutitem',
            name='about',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='pages.about', verbose_name='About us'),
        ),
        migrations.AlterField(
            model_name='aboutitem',
            name='description',
            field=models.TextField(max_length=500, verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='aboutitem',
            name='order',
            field=models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='Order'),
        ),
        migrations.AlterField(
            model_name='aboutitem',
            name='size',
            field=models.CharField(choices=[('about-item_third', '1/3'), ('about-item_half', '1/2'), ('about-item_full', '1/1')], default='about-item_half', max_length=16, verbose_name='Column size'),
        ),
        migrations.AlterField(
            model_name='aboutitem',
            name='title',
            field=models.CharField(max_length=100, verbose_name='Title'),
        ),
        migrations.AlterField(
            model_name='abroad',
            name='description',
            field=models.TextField(max_length=300, verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='abroad',
            name='title',
            field=models.CharField(max_length=255, verbose_name='Title'),
        ),
        migrations.AlterField(
            model_name='abroaditem',
            name='background_image',
            field=models.ImageField(upload_to='abroad_properties/%Y/%m/%d', verbose_name='Background image'),
        ),
        migrations.AlterField(
            model_name='abroaditem',
            name='description',
            field=models.TextField(max_length=500, verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='abroaditem',
            name='link',
            field=models.URLField(verbose_name='Link'),
        ),
        migrations.AlterField(
            model_name='abroaditem',
            name='order',
            field=models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='Order'),
        ),
        migrations.AlterField(
            model_name='abroaditem',
            name='photo_1',
            field=models.ImageField(upload_to='abroad_properties/%Y/%m/%d', verbose_name='Photo 1'),
        ),
        migrations.AlterField(
            model_name='abroaditem',
            name='photo_2',
            field=models.ImageField(upload_to='abroad_properties/%Y/%m/%d', verbose_name='Photo 2'),
        ),
        migrations.AlterField(
            model_name='abroaditem',
            name='title',
            field=models.CharField(max_length=100, verbose_name='Title'),
        ),
        migrations.AlterField(
            model_name='abroaditem',
            name='title_bg',
            field=models.CharField(max_length=15, verbose_name='Bg title'),
        ),
        migrations.AlterField(
            model_name='contact',
            name='email',
            field=models.EmailField(max_length=254, verbose_name='Email'),
        ),
        migrations.AlterField(
            model_name='contact',
            name='facebook',
            field=models.URLField(blank=True, null=True, verbose_name='Facebook'),
        ),
        migrations.AlterField(
            model_name='contact',
            name='instagram',
            field=models.URLField(blank=True, null=True, verbose_name='Instagram'),
        ),
        migrations.AlterField(
            model_name='contact',
            name='office_1',
            field=models.CharField(max_length=255, verbose_name='Office 1'),
        ),
        migrations.AlterField(
            model_name='contact',
            name='office_2',
            field=models.CharField(max_length=255, verbose_name='Office 2'),
        ),
        migrations.AlterField(
            model_name='contact',
            name='office_3',
            field=models.CharField(max_length=255, verbose_name='Office 3'),
        ),
        migrations.AlterField(
            model_name='contact',
            name='phone_1',
            field=models.CharField(max_length=30, verbose_name='Phone 1'),
        ),
        migrations.AlterField(
            model_name='contact',
            name='phone_2',
            field=models.CharField(max_length=30, verbose_name='Phone 2'),
        ),
        migrations.AlterField(
            model_name='contact',
            name='schedule',
            field=models.CharField(max_length=255, verbose_name='Schedule'),
        ),
        migrations.AlterField(
            model_name='contact',
            name='telegram',
            field=models.URLField(blank=True, null=True, verbose_name='Telegram'),
        ),
        migrations.AlterField(
            model_name='contact',
            name='viber',
            field=models.URLField(blank=True, null=True, verbose_name='Viber'),
        ),
        migrations.AlterField(
            model_name='course',
            name='auth_link',
            field=models.URLField(blank=True, null=True, verbose_name='Auth link'),
        ),
        migrations.AlterField(
            model_name='course',
            name='register_link',
            field=models.URLField(blank=True, null=True, verbose_name='Register link'),
        ),
        migrations.AlterField(
            model_name='home',
            name='about',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True, verbose_name='About us section'),
        ),
        migrations.AlterField(
            model_name='home',
            name='title',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='Title'),
        ),
    ]
