# Generated by Django 4.2.1 on 2023-07-09 09:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0011_alter_about_options_alter_aboutitem_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='vacantionpage',
            options={'verbose_name': 'Vacancies', 'verbose_name_plural': 'Vacancies'},
        ),
    ]
