# Generated by Django 4.2.1 on 2023-07-09 11:04

from django.db import migrations, models
import django.db.models.deletion
import parler.fields
import parler.models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0012_alter_vacantionpage_options'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='aboutitem',
            name='description',
        ),
        migrations.RemoveField(
            model_name='aboutitem',
            name='title',
        ),
        migrations.CreateModel(
            name='AboutItemTranslation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language_code', models.CharField(db_index=True, max_length=15, verbose_name='Language')),
                ('title', models.CharField(max_length=100, verbose_name='Title')),
                ('description', models.TextField(max_length=500, verbose_name='Description')),
                ('master', parler.fields.TranslationsForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='translations', to='pages.aboutitem')),
            ],
            options={
                'verbose_name': 'About us detail Translation',
                'db_table': 'pages_aboutitem_translation',
                'db_tablespace': '',
                'managed': True,
                'default_permissions': (),
                'unique_together': {('language_code', 'master')},
            },
            bases=(parler.models.TranslatableModel, models.Model),
        ),
    ]
