# Generated by Django 4.2.1 on 2023-07-09 11:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0013_remove_aboutitem_description_remove_aboutitem_title_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='aboutitem',
            name='description',
            field=models.TextField(default='2', max_length=500, verbose_name='Description'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='aboutitem',
            name='title',
            field=models.CharField(default='2', max_length=100, verbose_name='Title'),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='AboutItemTranslation',
        ),
    ]
