# Generated by Django 4.2.1 on 2023-07-09 11:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0014_aboutitem_description_aboutitem_title_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='about',
            name='description_1_uk',
            field=models.TextField(default='1', max_length=300, verbose_name='Description 1 of the section (Ukrainian)'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='about',
            name='description_2_uk',
            field=models.TextField(default='1', max_length=300, verbose_name='Description 2 of the section (Ukrainian)'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='about',
            name='title_1_uk',
            field=models.CharField(default='1', max_length=255, verbose_name='Title 1 of the section (Ukrainian)'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='about',
            name='title_2_uk',
            field=models.CharField(default='1', max_length=255, verbose_name='Title 2 of the section (Ukrainian)'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='aboutitem',
            name='description_uk',
            field=models.TextField(default=1, max_length=500, verbose_name='Description (Ukrainian)'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='aboutitem',
            name='title_uk',
            field=models.CharField(default=1, max_length=100, verbose_name='Title (Ukrainian)'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='about',
            name='description_1',
            field=models.TextField(max_length=300, verbose_name='Description 1 of the section (English)'),
        ),
        migrations.AlterField(
            model_name='about',
            name='description_2',
            field=models.TextField(max_length=300, verbose_name='Description 2 of the section (English)'),
        ),
        migrations.AlterField(
            model_name='about',
            name='title_1',
            field=models.CharField(max_length=255, verbose_name='Title 1 of the section (English)'),
        ),
        migrations.AlterField(
            model_name='about',
            name='title_2',
            field=models.CharField(max_length=255, verbose_name='Title 2 of the section (English)'),
        ),
        migrations.AlterField(
            model_name='aboutitem',
            name='description',
            field=models.TextField(max_length=500, verbose_name='Description (English)'),
        ),
        migrations.AlterField(
            model_name='aboutitem',
            name='title',
            field=models.CharField(max_length=100, verbose_name='Title (English)'),
        ),
    ]
