# Generated by Django 4.2.1 on 2023-07-09 11:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0015_about_description_1_uk_about_description_2_uk_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='abroad',
            name='description_uk',
            field=models.TextField(default='uk', max_length=300, verbose_name='Description (Ukrainian)'),
        ),
        migrations.AddField(
            model_name='abroad',
            name='title_uk',
            field=models.CharField(default='uk', max_length=255, verbose_name='Title (Ukrainian)'),
        ),
        migrations.AddField(
            model_name='abroaditem',
            name='description_uk',
            field=models.TextField(default='uk', max_length=500, verbose_name='Description (Ukrainian)'),
        ),
        migrations.AddField(
            model_name='abroaditem',
            name='title_uk',
            field=models.CharField(default='uk', max_length=100, verbose_name='Title (Ukrainian)'),
        ),
        migrations.AlterField(
            model_name='abroad',
            name='description',
            field=models.TextField(max_length=300, verbose_name='Description (English)'),
        ),
        migrations.AlterField(
            model_name='abroad',
            name='title',
            field=models.CharField(max_length=255, verbose_name='Title (English)'),
        ),
        migrations.AlterField(
            model_name='abroaditem',
            name='description',
            field=models.TextField(max_length=500, verbose_name='Description (English)'),
        ),
        migrations.AlterField(
            model_name='abroaditem',
            name='title',
            field=models.CharField(max_length=100, verbose_name='Title (English)'),
        ),
    ]
