# Generated by Django 4.2.1 on 2023-07-09 11:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0016_abroad_description_uk_abroad_title_uk_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='office_1_uk',
            field=models.CharField(default='uk', max_length=255, verbose_name='Office 1 (Ukrainian)'),
        ),
        migrations.AddField(
            model_name='contact',
            name='office_2_uk',
            field=models.CharField(default='uk', max_length=255, verbose_name='Office 2 (Ukrainian)'),
        ),
        migrations.AddField(
            model_name='contact',
            name='office_3_uk',
            field=models.CharField(default='uk', max_length=255, verbose_name='Office 3 (Ukrainian)'),
        ),
        migrations.AddField(
            model_name='contact',
            name='schedule_uk',
            field=models.CharField(default='uk', max_length=255, verbose_name='Schedule (Ukrainian)'),
        ),
        migrations.AlterField(
            model_name='contact',
            name='office_1',
            field=models.CharField(max_length=255, verbose_name='Office 1 (English)'),
        ),
        migrations.AlterField(
            model_name='contact',
            name='office_2',
            field=models.CharField(max_length=255, verbose_name='Office 2 (English)'),
        ),
        migrations.AlterField(
            model_name='contact',
            name='office_3',
            field=models.CharField(max_length=255, verbose_name='Office 3 (English)'),
        ),
        migrations.AlterField(
            model_name='contact',
            name='schedule',
            field=models.CharField(max_length=255, verbose_name='Schedule (English)'),
        ),
    ]
