# Generated by Django 4.2.1 on 2023-07-09 12:04

import ckeditor_uploader.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0018_home_about_uk_home_title_uk'),
    ]

    operations = [
        migrations.AlterField(
            model_name='home',
            name='about',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True, verbose_name='About us section (English)'),
        ),
        migrations.AlterField(
            model_name='home',
            name='about_uk',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True, verbose_name='About us section (Ukrainian)'),
        ),
        migrations.AlterField(
            model_name='home',
            name='title',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='Title (English)'),
        ),
        migrations.AlterField(
            model_name='home',
            name='title_uk',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='Title (Ukrainian)'),
        ),
    ]
